"use client";

import "./globals.css";
import store from "../redux/store/stores";
import { Provider } from "react-redux";
import Navbar from "../components/Navbar";
import Footer from "../components/footer";
import Head from "next/head";
// import ScrollToTop from "../components/scrolltoTop";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Localist.com</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Rubik:wght@300;400;500;700&display=swap"
        media="print"
        onload="this.media='all'"
      />
      <body>
        <Provider store={store}>
          {/* <ScrollToTop /> */}
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
